title: map.mrt.io
email: t@kalapun.com
description: > 
  Map, Foursquare & routes playground
  Search spots on map vie Fsq & create routes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://map.mrt.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  xslim

# Build settings
markdown: kramdown
